#!/bin/bash
exec_time=$( date '+%H' );
echo $exec_time;
if [[ $exec_time -gt 12 ]]
then
  echo "Good Eve";
  feh --bg-scale --randomize $HOME/.config/wallpapers/gruvbox/dark/;
else
  echo "Good Mor";
  feh --bg-scale --randomize $HOME/.config/wallpapers/gruvbox/light/;
fi
